program = { statement } ;

statement = variable_decl
          | assignment
          | print_stmt
          | input_stmt
          | if_stmt
          | loop_stmt
          | function_def
          | function_call ;

variable_decl = "let" identifier "=" expression "." ;

assignment = "set" identifier "to" expression "." ;

print_stmt = "print" expression "." ;

input_stmt = "input" identifier "with" string "." ;

if_stmt = "when" condition "then"
            { statement }
          [ "else"
            { statement } ]
          "stop" "." ;

loop_stmt = "keep" "going" ":"
              { statement }
            "until" condition "." ;

function_def = "define" "task" identifier
                 { statement }
               "end" "task" "." ;

function_call = identifier "." ;

expression = term { ("+" | "-") term } ;

term = factor { ("*" | "/") factor } ;

factor = number
       | string
       | function_call
       | identifier
       | list
       | "(" expression ")"
       | modulo_expr ;

modulo_expr = "remainder" "of" factor "/" factor ;

list = "[" [ expression { "," expression } ] "]" ;

condition = expression comparator expression ;

comparator = ">" | "<" | "==" | ">=" | "<=" ;

identifier = ? variable name ? ;

number = ? number value ? ;

string = ? text inside quotes ? ;
